[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "yolov9"
version = "0.1.0"

[tool.setuptools]
packages = ["models", "utils"]
py-modules = ["__init__", "export"] # dash, not underscore